const mazo = [
  { valor: 1, palo: "bastos" },
  { valor: 1, palo: "espadas" },
  { valor: 1, palo: "copas" },
  { valor: 1, palo: "oros" },
  { valor: 2, palo: "bastos" },
  { valor: 2, palo: "espadas" },
  { valor: 2, palo: "copas" },
  { valor: 2, palo: "oros" },
  { valor: 3, palo: "bastos" },
  { valor: 3, palo: "espadas" },
  { valor: 3, palo: "copas" },
  { valor: 3, palo: "oros" },
  { valor: 4, palo: "bastos" },
  { valor: 4, palo: "espadas" },
  { valor: 4, palo: "copas" },
  { valor: 4, palo: "oros" },
  { valor: 5, palo: "bastos" },
  { valor: 5, palo: "espadas" },
  { valor: 5, palo: "copas" },
  { valor: 5, palo: "oros" },
  {valor: 6 , palo: "bastos"},
  {valor: 6 , palo: "espadas"},
  {valor: 6 , palo: "copas"},
  {valor: 6 , palo: "oros"},
  {valor: 7 , palo: "bastos"},
  {valor: 7 , palo: "espadas"},
  {valor: 7 , palo: "copas"},
  {valor: 7 , palo: "oros"},
  {valor: 8 , palo: "bastos"},
  {valor: 8 , palo: "espadas"},
  {valor: 8 , palo: "copas"},
  {valor: 8 , palo: "oros"},
  {valor: 9 , palo: "bastos"},
  {valor: 9 , palo: "espadas"},
  {valor: 9 , palo: "copas"},
  {valor: 9 , palo: "oros"},
  {valor: 10 , palo: "bastos"},
  {valor: 10 , palo: "espadas"},
  {valor: 10 , palo: "copas"},
  {valor: 10 , palo: "oros"},
  {valor: 11 , palo: "bastos"},
  {valor: 11 , palo: "espadas"},
  {valor: 11 , palo: "copas"},
  {valor: 11 , palo: "oros"},
  {valor: 12 , palo: "bastos"},
  {valor: 12 , palo: "espadas"},
  {valor: 12 , palo: "copas"},
  {valor: 12 , palo: "oros"}
];


export default mazo;
